version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_train_schedule
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: train_schedule
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
